# Site settings ...
uri: nevarez.dev
url: https://nevarez.dev
name: JC
title: Mangan Jekyll Theme
email: example@domain.com
author: JC
keywords: "Your, Keyword, Here"
description: "Cyber Security Practitioner"
social_username: username

# Build settings ...
sass:
  style: compressed
markdown: kramdown
paginate: 5
permalink: /post/:title
paginate_path: "/page/:num/"
exclude:
  - README.md

# Plugins ...
plugins:
  - jekyll-paginate
  - jemoji
